id: IA88823D8
legacy_id: P000551
ocr_import_info:
  bdrc_scan_id: W27597
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:14:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:30:59.449113+00:00'
last_modified: 2022-09-02 15:31:10.746422
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27597
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27597
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨོ་རྒྱན་གུ་རུ་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དོན་ལྡན་དང་འབྲེལ་བའི་སྙིང་པོ་རྡོ་རྗེའི་སྒྲ་དབྱངས་ཀྱི་ཕྲེང་བ།
  author: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7736356369655611
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I4505:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4505
      total_pages: 112
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4505.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7736356369655611
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
